config/routes.rb
EngineeringCalculator::Application.routes.draw do
  
  get "pages/home"
  resources  :engineers
  root :to => "engineer#index"
  
  match '/calculators', :to => "engineer#index"
  match '/isentropic', :to => "engineer#isentropic"
  match '/normal_shock', :to => "engineer#normal_shock"
  match '/fanno', :to => "engineer#fanno"
  match '/rayleigh', :to => "engineer#rayleigh"
  match '/oblique', :to => "engineer#oblique"
  match '/prandtlmeyer', :to => "engineer#prandtlmeyer"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/engineer_controller.rb
class EngineerController < ApplicationController
  
  def index
    @title = "Calculators"
  end
  
  def fanno
    @title = "Fanno Flow"
    meta :title => @title, :description => "Solves Fanno Flow Problems", :keywords => %w(Engineering Calculator Fanno Flow)
  end
  
  def isentropic
    @title = "Isentropic Flow"
    meta :title => @title, :description => "Solves Isentropic Flow Problems", :keywords => %w(Engineering Calculator Isentropic Flow)
  end
  
  def normal_shock
    @title = "Normal Shock"
    meta :title => @title, :description => "Solves Normal Shock Problems", :keywords => %w(Engineering Calculator Shock)
  end
  
  def oblique
    @title = "Oblique Shock"
    meta :title => @title, :description => "Solves Oblique Shock Problems", :keywords => %w(Engineering Calculator Oblique Shock)
  end
  
  def prandtlmeyer
    @title = "Pandtl-Meyer"
    meta :title => @title, :description => "Solves Prandtl-Meyer Problems", :keywords => %w(Engineering Calculator Prandtl Meyer)
  end
  
  def rayleigh
    @title = "Rayleigh Flow"
    meta :title => @title, :description => "Solves Rayleigh Flow Problems", :keywords => %w(Engineering Calculator Rayleigh Flow)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engineer_helper.rb
module EngineerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/engineer/fanno.html.erb
<div class="page-header">
  <h1>Fanno Flow</h1>
</div>

<form name="fanno_form">
	
	<label for="m_in">Mach Number</label>
	<div class="input">
		<input type="text" name="m_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="gamma_in">Gamma</label>
	<div class="input">
		<input type="text" name="gamma_in" value="1.4" size="12" maxlength="12">
	</div>
	
	<div class="actions">
		<input type=button value="Calculate" class="btn primary" onClick="fanno()";>
	</div>
	
	<h3>Results</h3>
	
	<div class="row">
		<div class="span5">
			<table>
				<thead>
					<tr>
						<th>Ratio</th>
						<th>Value</th>
					</tr>
				</thead>
				
				<tbody>
					<tr>
						<td>$ \frac{P}{P^{*}} $</td>
						<td><div id="p_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{\rho}{\rho^{*}} $</td>
						<td><div id="rho_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{T}{T^{*}} $</td>
						<td><div id="t_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{U}{U^{*}} $</td>
						<td><div id="u_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P_0}{(P_0)^{*}} $</td>
						<td><div id="po_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{4 F L^{*}}{D_h} $</td>
						<td><div id="fanno_param">-</div></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>

<h5><%= link_to "Equations", "https://s3.amazonaws.com/EngineeringCalc/Fanno.pdf"%></h5>

app/views/engineer/index.html.erb
<div class="page-header">
  <h1>Engineering Calculators</h1>
</div>

<h2>Gas Dynamics</h2>
<ul>
	<li><%= link_to "Isentropic Flow", isentropic_path %></li>
	<li><%= link_to "Normal Shock", normal_shock_path %></li>
	<li><%= link_to "Fanno Flow", fanno_path %></li>
	<li><%= link_to "Rayleigh Flow", rayleigh_path %></li>
	<li><%= link_to "Oblique Shock", oblique_path %></li>
	<li><%= link_to "Prandtl-Meyer", prandtlmeyer_path %></li>
</ul>

app/views/engineer/isentropic.html.erb
<div class="page-header">
  <h1>Isentropic Flow</h1>
</div>

<form name="isentropic_form">
	
	<label for="m_in">Mach Number</label>
	<div class="input">
		<input type="text" name="m_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="gamma_in">Gamma</label>
	<div class="input">
		<input type="text" name="gamma_in" value="1.4" size="12" maxlength="12">
	</div>
	
	<div class="actions">
		<input type=button value="Calculate" class="btn primary" onClick="isentropic_flow()";>
	</div>
	
	<div class="row">
		
		<div class="span5">
			<h3>Results</h3>
			<table>
				<thead>
					<tr>
						<th>Ratio</th>
						<th>Value</th>
					</tr>
				</thead>
			
				<tbody>
					<tr>
						<td>$ \frac{T}{T_0} $</td>
						<td><div id="ratio_t">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P}{P_0} $</td>
						<td><div id="ratio_p">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{\rho}{\rho_0} $</td>
						<td><div id="ratio_rho">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{A}{A^{*}} $</td>
						<td><div id="ratio_a">-</div></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>

<h5><%= link_to "Equations", "https://s3.amazonaws.com/EngineeringCalc/Isentropic.pdf"%></h5>

app/views/engineer/normal_shock.html.erb
<div class="page-header">
  <h1>Normal Shock</h1>
</div>

<form name="normal_shock_form">
	
	<label for="mx_in">Mach Number X</label>
	<div class="input">
		<input type="text" name="mx_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="gamma_in">Gamma</label>
	<div class="input">
		<input type="text" name="gamma_in" value="1.4" size="12" maxlength="12">
	</div>
	
	<div class="actions">
		<input type=button value="Calculate" class="btn primary" onClick="normal_shock()";>
	</div>
	
	<h3>Results</h3>
	
	<div class="row">
		<div class="span5">
			<table>
				<thead>
					<tr>
						<th>Ratio</th>
						<th>Value</th>
					</tr>
				</thead>
				
				<tbody>
					<tr>
						<td>$ m_y $</td>
						<td><div id="my">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P_y}{P_x} $</td>
						<td><div id="py_px">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{\rho_y}{\rho_x} $</td>
						<td><div id="rhoy_rhox">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{T_y}{T_x} $</td>
						<td><div id="ty_tx">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P_0y}{P_0x} $</td>
						<td><div id="poy_pox">-</div></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>

<h5><%= link_to "Equations", "https://s3.amazonaws.com/EngineeringCalc/NormalShock.pdf"%></h5>

app/views/engineer/oblique.html.erb
<div class="page-header">
  <h1>Oblique Shock</h1>
</div>

<form name="oblique_form">
	
	<label for="m_in">Mach Number X</label>
	<div class="input">
		<input type="text" name="mx_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="delta_in">Turning Angle </label>
	<div class="input">
		<input type="text" name="delta_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="gamma_in">Gamma</label>
	<div class="input">
		<input type="text" name="gamma_in" value="1.4" size="12" maxlength="12">
	</div>
	
	<div class="actions">
		<input type=button value="Calculate" class="btn primary" onClick="oblique()";>
	</div>
	
	<h3>Results</h3>
	
	<div class="row">
		<div class="span5">
			<table>
				<thead>
					<tr>
						<th>Ratio</th>
						<th>Value</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>$ m_y $</td>
						<td><div id="my">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P_y}{P_x} $</td>
						<td><div id="ratio_p">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{T_y}{T_x} $</td>
						<td><div id="ratio_t">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{\rho_y}{\rho_x} $</td>
						<td><div id="ratio_rho">-</div></td>
					</tr>
					<tr>
						<td>$ \sigma $</td>
						<td><div id="beta">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{(P_0)_y}{(P_0)_x} $</td>
						<td><div id="ratio_po">-</div></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>
<h5><%= link_to "Equations", "https://s3.amazonaws.com/EngineeringCalc/Oblique.pdf"%></h5>

app/views/engineer/prandtlmeyer.html.erb
<div class="page-header">
  <h1>Prandtl-Meyer</h1>
</div>

<form name="prandtl_form">
	
	<label for="mx_in">Mach Number</label>
	<div class="input">
		<input type="text" name="mx_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="turning_in">Turning Angle</label>
	<div class="input">
		<input type="text" name="turning_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="gamma_in">Gamma</label>
	<div class="input">
		<input type="text" name="gamma_in" value="1.4" size="12" maxlength="12">
	</div>
	
	<div class="input">
  	<ul class="inputs-list">
    	<li>
      	<label>
        	<input type="radio" name="optionsPrandtl" value="1" checked="checked" />
          	<span>Isentropic Compression</span>
        </label>
      </li>

      <li>
      	<label>
        	<input type="radio" name="optionsPrandtl" value="2" />
        	<span>Isentropic Expansion</span>
       	</label>
			</li>
		</ul>
 	</div>

	<div class="actions">
		<input type=button value="Calculate" class="btn primary" onClick="prandtl()";>
	</div>
	
	<h3>Results</h3>
	
	<div class="row">
		<div class="span5">
			<table>
				<thead>
					<tr>
						<th>Ratio</th>
						<th>Value</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<td>$ \frac{T_y}{T_x} $</td>
						<td><div id="t_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P_y}{P_x} $</td>
						<td><div id="p_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{\rho_y}{\rho_x} $</td>
						<td><div id="rho_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ m_y $</td>
						<td><div id="my">-</div></td>
					</tr>
					<tr>
						<td>$ \nu_x $</td>
						<td><div id="nux">-</div></td>
					</tr>
					<tr>
						<td>$ \nu_y $</td>
						<td><div id="nuy">-</div></td>
					</tr>
					<tr>
						<td>$ \mu_x $</td>
						<td><div id="mux">-</div></td>
					</tr>
					<tr>
						<td>$ \mu_y $</td>
						<td><div id="muy">-</div></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>

<h5><%= link_to "Equations", "https://s3.amazonaws.com/EngineeringCalc/Prandtl.pdf"%></h5>

app/views/engineer/rayleigh.html.erb
<div class="page-header">
  <h1>Rayleigh Flow</h1>
</div>

<form name="rayleigh_form">
	
	<label for="m_in">Mach Number</label>
	<div class="input">
		<input type="text" name="m_in" value="1" size="12" maxlength="12">
	</div>
	
	<label for="gamma_in">Gamma</label>
	<div class="input">
		<input type="text" name="gamma_in" value="1.4" size="12" maxlength="12">
	</div>
	
	<div class="actions">
		<input type=button value="Calculate" class="btn primary" onClick="rayleigh()";>
	</div>
	
	<h3>Results</h3>
	
	<div class="row">
		<div class="span5">
			<table>
				<thead>
					<tr>
						<th>Ratio</th>
						<th>Value</th>
					</tr>
				</thead>
				
				<tbody>
					<tr>
						<td>$ \frac{P}{P^{*}} $</td>
						<td><div id="p_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{\rho}{\rho^{*}} $</td>
						<td><div id="rho_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{T}{T^{*}} $</td>
						<td><div id="t_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{U}{U^{*}} $</td>
						<td><div id="u_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{P_0}{(P_0)^{*}} $</td>
						<td><div id="po_ratio">-</div></td>
					</tr>
					<tr>
						<td>$ \frac{T_0}{(T_0)^{*}} $</td>
						<td><div id="to_ratio">-</div></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>
<h5><%= link_to "Equations", "https://s3.amazonaws.com/EngineeringCalc/Rayleigh.pdf"%></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Engineering Calculator | <%= @title %></title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
		<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
	 	<%= stylesheet_link_tag    "application" %>
	 	<%= javascript_include_tag "application" %>
	 	<%= csrf_meta_tags %>
		<%= metamagic :title => "Engineering Calculator", :description => "Calculates various Engineering Problems", :keywords => %w(Engineering Calculator) %>
	
		<script type="text/javascript"
		  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
		</script>
		
		<script type="text/x-mathjax-config">
		  MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
		</script>
		
		<script type="text/javascript">
		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/plusone.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
		
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-10268398-2']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	</head>
	
	<body>
		<div class="topbar-wrapper" style="z-index: 5;">
			<div class="topbar" data-dropdown="dropdown">
		   	<div class="topbar-inner">
	     		<div class="container">
						<a class="brand" href="/">Engineering Calculator</a>
	          <ul class="nav">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle">Gas Dynamics</a>
							  <ul class="dropdown-menu">
							  	<li><%= link_to "Isentropic Flow", isentropic_path %></li>
									<li><%= link_to "Normal Shock", normal_shock_path %></li>
									<li><%= link_to "Fanno Flow", fanno_path %></li>
									<li><%= link_to "Rayleigh Flow", rayleigh_path %></li>
									<li><%= link_to "Oblique Shock", oblique_path %></li>
									<li><%= link_to "Prandtl-Meyer", prandtlmeyer_path %></li>
								</ul>
							</li>
						</ul>
					</div>
	 			</div>
	    </div>
		</div>
		
		<div class="container">
			<div class="content">
				<div class="gplus">
					<g:plusone></g:plusone>
				</div>
				<%= yield %>
			</div>

			<footer>
				<p>&copy; Muntaner Software 2011</p>
			</footer>
		</div>
	</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>